apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: pruebas
spec:
  selector:
    app: postgresdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
