apiVersion: v1
kind: Service
metadata:
  name:  mysql-service
  namespace: pruebas
spec:
  selector:
    app:  mysqldb
  ports:
    - protocol: TCP
      port:  3306
      targetPort:  3306
  type:  LoadBalancer
