apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: pruebas
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 9000
  type: LoadBalancer
