apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  namespace: pruebas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:latest
          ports:
            - containerPort: 9000
          env:
            - name: SONARQUBE_WEB_CONTEXT
              value: /
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"