apiVersion: v1
kind: LimitRange
metadata:
  name:  limitar-rango
spec:
  limits:
    - type: Container
      max: 
        memory: 1Gi
      min:
        memory: 100Mi
      default:
        memory: 200Mi
      defaultRequest:
        memory: 150Mi
      maxLimitRequestRatio:
        memory: 4
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi