apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  postgres-pvc
  namespace: pruebas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Tamanho del almacenamiento